### ISSUE TITLE
Kick instead of ban for nitro scams

### ISSUE THREAD

**Issue by end-me-please** [Anuken/CoreBot#30]
even if a user does not regain access to their account, banning them prevents them from re-joining the server with a different account that has the same e-mail or phone number.

**Comment by Anuken** [comment]
> besides that, if the filter caught + deleted the scam, is more than a timeout necessary?

Yes, because the scammers controlling the account could do it again after the timeout.

> even if a user does not regain access to their account, banning them prevents them from re-joining the server with a different account that has the same e-mail or phone number.

It's still a compromised account that could be used to re-join and re-scam the server. Perhaps there should be an easier way to notify me/the mods of a banned account, but for now the only option is to open an issue here (which should be part of the ban message).
